-- 코드를 입력하세요
WITH BTS AS (
    SELECT A.AUTHOR_ID AUTHOR_ID, A.AUTHOR_NAME AUTHOR_NAME, B.CATEGORY CATEGORY, 
      (S.SALES * B.PRICE) TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE < '2022-02-01'
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM BTS
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;