-- 코드를 작성해주세요
# SELECT C.ID
# FROM ECOLI_DATA A
# JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
# JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID
# WHERE A.PARENT_ID IS NULL
# ORDER BY C.ID;

WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, C.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN CTE C
    ON E.PARENT_ID = C.ID
)
SELECT ID
FROM CTE
WHERE GENERATION = 3
ORDER BY ID;