-- 코드를 작성해주세요
SELECT E.ID, IFNULL(T.CHILD_COUNT, 0) CHILD_COUNT
FROM (ECOLI_DATA E
LEFT JOIN 
(SELECT A.ID, COUNT(A.ID) CHILD_COUNT
FROM ECOLI_DATA A 
JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
GROUP BY A.ID) T
ON E.ID = T.ID)
WHERE E.ID
