-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE AS A
WHERE (SELECT COUNT(*) 
       FROM ONLINE_SALE
       WHERE USER_ID = A.USER_ID AND PRODUCT_ID = A.PRODUCT_ID 
      ) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;