-- 코드를 입력하세요
SELECT P.PRODUCT_CODE PRODUCT_CODE, SUM(O.SALES_AMOUNT * P.PRICE) SALES
FROM OFFLINE_SALE O 
JOIN PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;