# # -- 코드를 입력하세요
WITH CAR_CTE AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE NOT (START_DATE > '2022-11-30' OR 
                            END_DATE < '2022-11-01'))
        AND CAR_TYPE IN ('SUV', '세단')
),
PLAN_CTE AS (
    SELECT CAR_TYPE, DISCOUNT_RATE * 0.01 DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('SUV', '세단')
)
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((C.DAILY_FEE-(C.DAILY_FEE*P.DISCOUNT_RATE))*30) FEE
FROM CAR_CTE C
JOIN PLAN_CTE P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.DAILY_FEE-(C.DAILY_FEE*P.DISCOUNT_RATE))*30 >= 500000 AND 
    (C.DAILY_FEE-(C.DAILY_FEE*P.DISCOUNT_RATE))*30 < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
