-- 코드를 입력하세요
WITH INTACT_ANIMAL AS (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) 
SELECT O.ANIMAL_ID ANIMAL_ID, O.ANIMAL_TYPE ANIMAL_TYPE, O.NAME NAME
FROM ANIMAL_OUTS O
JOIN INTACT_ANIMAL I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY ANIMAL_ID;