-- 코드를 작성해주세요
WITH RECURSIVE HIERARCHY_CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, H.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN HIERARCHY_CTE H 
    ON E.PARENT_ID = H.ID
)
SELECT COUNT(*) COUNT, H.GENERATION
FROM HIERARCHY_CTE H
LEFT JOIN ECOLI_DATA E
ON H.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY H.GENERATION
ORDER BY H.GENERATION
;