-- 코드를 입력하세요
WITH AVAILABILITY_CTE AS (
    SELECT HISTORY_ID, (CASE 
    WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
    ELSE 0
    END) AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT C.CAR_ID, (CASE SUM(A.AVAILABILITY) 
                WHEN 1 THEN '대여중'
                ELSE '대여 가능'
                END) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN AVAILABILITY_CTE A
ON C.HISTORY_ID = A.HISTORY_ID
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;