-- 코드를 입력하세요
WITH RECURSIVE HOUR_CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
    FROM HOUR_CTE
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(A.ANIMAL_ID) COUNT
FROM HOUR_CTE H
LEFT JOIN ANIMAL_OUTS A
ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY HOUR
;