-- 코드를 작성해주세요
WITH CTE AS(
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT C.YEAR, C.MAX_SIZE - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E
LEFT JOIN CTE C
ON YEAR(E.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY C.YEAR, YEAR_DEV;