-- 코드를 작성해주세요
WITH CTE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT I.ID, F.FISH_NAME, C.LENGTH
FROM FISH_INFO I
JOIN CTE C
ON I.FISH_TYPE = C.FISH_TYPE AND I.LENGTH = C.LENGTH
JOIN FISH_NAME_INFO F
ON C.FISH_TYPE = F.FISH_TYPE
ORDER BY I.ID;