-- 코드를 작성해주세요
WITH TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT T.SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM HR_EMPLOYEES H
JOIN TOTAL_SCORE T 
ON H.EMP_NO = T.EMP_NO
WHERE T.SCORE = (SELECT MAX(SCORE) FROM TOTAL_SCORE)
;