-- 코드를 입력하세요
WITH BS AS (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
)
SELECT B.CATEGORY CATEGORY, SUM(S.SALES) TOTAL_SALES
FROM BOOK B
JOIN BS S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
;