-- 코드를 입력하세요
WITH PRICE_CTE AS (
    SELECT PRODUCT_ID, TRUNCATE(PRICE / 10000, 0) * 10000 만원단위가격대 
    FROM PRODUCT
)
SELECT R.만원단위가격대 AS PRICE_GROUP, COUNT(*) PRODUCTS
FROM PRODUCT P
JOIN PRICE_CTE R ON P.PRODUCT_ID = R.PRODUCT_ID
GROUP BY R.만원단위가격대
ORDER BY PRICE_GROUP
;
